WORK_GENE_DIR: "/data_scripts/Somatic-Mutations/scripts_gene_analysis/"
DATASET: "datasets/full_columns_data.tsv"
GMT_FOLDER: "/data_scripts/Somatic-Mutations/scripts_gene_analysis/gmt_file/"
GENE_FILES_FOLDER: "/data_scripts/Somatic-Mutations/scripts_gene_analysis/gene_folder/"

HALLMARK_RESULTS: "scripts_gene_analysis/hallmark/ALL_gene_list.txt_enrichment_results.csv"

CLL_ENR_RESULTS: "/scripts_gene_analysis/hallmark/ern_res_p_values_15/CLL_gene_list_top_enriched_pathways.tsv"

