# Seed for reproducibility
SEED: 42

# Data path
WORK_DIR: 'Somatic-Mutations/'
DATASET: 'datasets/full_data.tsv'
OUTPUT_DIR: 'result_files/'
# Correlation matrix cramers_v
CORR_IMAGE: 'result_files/categorical_correlation.png'
CORR_RESULTS: 'result_files/correlation_results.txt'
# Feature Selection
ANOVA: 'result_files/ANOVA_F_value_feature_importance.png'
MIT: 'result_files/mutual_info_class.png'
# Lazy predict results
LZP_RESULTS: 'result_files/lzp_results.tsv'
# Random Forest results
CROSS_VAL: 'result_files/cv_score.txt'
ACCURACY: 'result_files/accuracy.txt'
REPORT_RF: 'result_files/class_report.txt'
CONFUSION_MTX: 'result_files/confusion_mtx.txt'

# Epochs
EPOCHS: 20

# MLP Hyperparameters optimization
PARAM_GRID: {
  "dropout_rate": [0.1, 0.2, 0.3, 0.4, 0.5], 
  "learning_rate": [0.001, 0.002, 0.003, 0.004, 0.005],
  "batch_size": [35, 70, 100, 200, 500],
  "neurons_1st_layer": [16, 32, 64, 128, 256],
  "neurons_2nd_layer": [32, 64, 128, 256, 512]
}

# Final Parameters
PARAM_GRID: {
  "dropout_rate": [0.1], 
  "learning_rate": [0.002],
  "batch_size": [35],
  "neurons_1st_layer": [16],
  "neurons_2nd_layer": [32]
}

# Multilayer Perceptron
MLP_RESULTS: 'result_files/mlp_folder/validation_results.txt'