#### Upstream analysis ####

# Dataset for the analysis of somatic mutations
DATASET_SOMATIC_MUTATION: "datasets/full_columns_data.tsv"
# Directory for Leukemia gene lists
GENE_FILES_FOLDER: "scripts_gene_analysis/gene_folder/"
# Output directory for Leukemia gene lists
HALLMARK_RESULTS: "scripts_gene_analysis/hallmark/"
# Directory for Over-representation analysis
ENRICH_FOLDER: "scripts_gene_analysis/hallmark/ora_results/"
# Directory for Over-representation analysis: first 15 most significant pathways
ENR_15_FOLDER: "scripts_gene_analysis/hallmark/ern_res_p_values_15/"
# Directory for the plots
ENR_PLOTS: "scripts_gene_analysis/hallmark/enr_plots/"
# AML files to check if files exist in ENRICH_FOLDER
AML_ENRICH: "scripts_gene_analysis/hallmark/ora_results/Acute Lymphoblastic Leukemia_enrichment_results.csv"
# AML files to check if files exist in ENR_15_FOLDER
AML_ENRICH_15: "scripts_gene_analysis/hallmark/ern_res_p_values_15/LAML_gene_list_top_enriched_pathways.tsv"
# AML file: Check if file exists in ENR_PLOTS
AML_PLOT: "scripts_gene_analysis/hallmark/enr_plots/Acute Myeloid Leukemia_plot.png"

#### Downstream analysis ####

# Seed for reproducibility
SEED: 42
# Assess statistical significance of the correlations
SIGNIFICANT_THRESHOLD: 0.050
# Optimal number of trees
N_OPTIMAL_TREES: 200
# Epochs
EPOCHS: 100

# Data path
WORK_DIR: 'Somatic-Mutations/'
DATASET: 'datasets/full_data.tsv'
OUTPUT_DIR: 'result_files/'
# Correlation matrix cramers_v
CORR_FOLDER: "result_files/correlation_folder/"


# Lazy predict results
LZP_RESULTS: 'result_files/lzp/'

# Random Forest results
RF_FOLDER: "result_files/rf_folder"
CROSS_VAL: 'result_files/rf_folder/cv_score.txt'
ACCURACY: 'result_files/rf_folder/accuracy.txt'
RF_BEST_PARAMS: 'result_files/rf_folder/rf_best_params.txt'
REPORT_RF: 'result_files/rf_folder/class_report.txt'
CONFUSION_MTX: 'result_files/rf_folder/confusion_mtx.txt'

# Best parameters MLP
BEST_PARAMS: 'result_files/mlp_folder/best_params.txt'

# Multilayer Perceptron
MLP_RESULTS: 'result_files/mlp_folder/'

# MLP best model 
BEST_MODEL: "result_files/mlp_folder/MlpModel.keras"
